defmodule ArmchairMetropolistWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :armchair_metropolist

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_armchair_metropolist_key",
    signing_salt: "ccKXd5/j",
    same_site: "Lax",
    # 90 days — matches :snapshot_retention_days (config.exs). Without a max_age,
    # Plug.Session emits no expires/max-age attribute at all and the cookie is
    # browser-session scoped: it dies the moment the browser closes, not merely
    # when explicitly cleared. That is a far more common way to lose a city than
    # the "cleared cookie" spec §10 accepts, and it silently breaks the promise the
    # retention window and the UI copy ("this city lives in this browser") both
    # make. Keep this in step with :snapshot_retention_days by hand; nothing
    # currently derives one from the other.
    max_age: 90 * 24 * 60 * 60,
    # Belt-and-braces alongside config/prod.exs's `force_ssl`: that already
    # upgrades every request to HTTPS in production, so this flag is inert there
    # today, but the session cookie should not depend on a setting that lives in a
    # different file to stay off cleartext.
    secure: true
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :armchair_metropolist,
    gzip: not code_reloading?,
    only: ArmchairMetropolistWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :armchair_metropolist
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ArmchairMetropolistWeb.Router
end
